### ISSUE TITLE
zCAP-LD w/HTTP Signatures

### ISSUE THREAD

**Issue by llorllale** [trustbloc/edge-core#75]
**Requirement**

It is desired to enable an authorization strategy using a form of authorization capabilities where the sender's authentication and capability invocation are transmitted in HTTP message headers using HTTP signatures.

The _capability invoker_ crafts an HTTP message with special headers indicating their KID, the content being signed over, as well as the actual signature itself. The sender's signing key is presumed to have been communicated out of band to the verifier.

Initial signing algorithm supported will be ECDSA using curve P-256 and SHA-256.

Note: we should not use `(algorithm)` since it enables attack vectors in some cases (eg. "ecdsa-sha256" [section 5.1.2](https://tools.ietf.org/html/draft-ietf-httpbis-message-signatures-00#section-5.1.2)).

**We will use [igor-pavlenko/httpsignatures-go](https://github.com/igor-pavlenko/httpsignatures-go) to create and parse HTTP signatures as per the HTTPbis draft.**

----

**Breakdown**

- [x] ~~parse headers (including new headers) #79~~
- [x] ~~canonicalization of header fields #88~~
- [x] ~~sign and add `Signature` header using ECDSA with curve P-256 and SHA-256~~
- [x] reusable middleware to wrap existing handlers #101
- [x] ~~API to create `*http.Request`s with signatures~~
- [x] godocs + examples (examples can be found in the tests)
- [x] ~~PR httpwg/http-extensions#1297 will pull in [structured headers](https://tools.ietf.org/html/draft-ietf-httpbis-header-structure). Will need to refactor. Parsers:~~
  - https://github.com/dunglas/httpsfv (Go)
  - https://pypi.org/project/http-sfv/ (Python)
- [x] parse zcap-ld #92
- [x] validate ld proof #95 
- [x] create API #97
- [x] support for `did:key` #98 
- [x] `httpsignatures.Secrets` implementation for `did:key` (for verification) #105
- [x] integrate httpsignatures-go with KMS #106

----

**Known spec issues #89 :**

* Missing documentation on certain fields of the JSONLD security vocabulary:
  * invoker: https://github.com/w3c-ccg/security-vocab/issues/24
  * invocationTarget: https://github.com/w3c-ccg/security-vocab/issues/25
  * parentCapability: https://github.com/w3c-ccg/security-vocab/issues/67
  * allowedAction: https://github.com/w3c-ccg/security-vocab/issues/67
  * capabilityChain: https://github.com/w3c-ccg/security-vocab/issues/28
  * delegator: https://github.com/w3c-ccg/security-vocab/issues/26

----

**References**

* [Signing HTTP Messages](https://tools.ietf.org/html/draft-ietf-httpbis-message-signatures)
* [GitHub Issues](https://github.com/w3c-ccg/http-signatures/issues)
* [digitalbazaar/http-signature-zcap-verify](https://github.com/digitalbazaar/http-signature-zcap-verify)
* [digitalbazaar/bedrock-edv-storage](https://github.com/digitalbazaar/bedrock-edv-storage)
