### ISSUE TITLE
httpsig: spec feedback and followup

### ISSUE THREAD

**Issue by llorllale** [trustbloc/edge-core#89]
- [ ] letter case for content identifiers: httpwg/http-extensions#1308
- [ ] which parameters are tokens and which are quoted-strings?: httpwg/http-extensions#1307
- [ ] http header line folding: httpwg/http-extensions#:1306
- [ ] datatypes of parameters: httpwg/http-extensions#1305
- [ ] expected behaviour when encountering unrecognized parameters: httpwg/http-extensions#1304
- [ ] use of parenthesis around some content identifiers: httpwg/http-extensions#1303
